project:
  type: website
  output-dir: docs

website:
  title: "PM566/PM592 Finals"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: PM566 Final
      - href: PM592.qmd
        text: PM592 Final


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



